remote_id = '392865941'
kb_layout_type = ''
size = [
    0,
    0,
    0,
    0,
]
fav = []

[options]
remote-menubar-drag-left = '0.0'
remote-menubar-drag-right = '1.0'

[ui_flutter]
wm_RemoteDesktop = '{"width":1300.0,"height":740.0,"offsetWidth":0.0,"offsetHeight":0.0,"isMaximized":true}'
remoteMenubarState = '{"pin":true}'
wm_Main = '{"width":800.0,"height":600.0,"offsetWidth":0.0,"offsetHeight":0.0,"isMaximized":false}'
wm_PortForward = '{"width":1920.0,"height":1080.0,"offsetWidth":0.0,"offsetHeight":0.0,"isMaximized":true}'
wm_Unknown = '{"width":1920.0,"height":1080.0,"offsetWidth":0.0,"offsetHeight":0.0,"isMaximized":true}'
peer-sorting = 'Remote ID'
wm_FileTransfer = '{"width":1920.0,"height":1080.0,"offsetWidth":0.0,"offsetHeight":0.0,"isMaximized":true}'
